# Generated by Django 3.1.6 on 2021-04-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='numOfGroup',
            new_name='skills',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='leader',
            new_name='teamLeader',
        ),
        migrations.RemoveField(
            model_name='post',
            name='needed',
        ),
        migrations.AddField(
            model_name='post',
            name='numOfPeople',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='stillNeed',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='post',
            name='teamName',
            field=models.TextField(default='hello world'),
        ),
    ]
