# Generated by Django 3.1.6 on 2021-04-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210427_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='skills',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='teamID',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='teamName',
            field=models.TextField(default=''),
        ),
    ]
